name: hello world

on:
  
  schedule:
    - cron : "*/2 * * * *"
  workflow_dispatch:

jobs: 
  hello:
    runs-on: ubuntu-latest
    name: my-job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: hello
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
